### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MiLeX84** [mistenkt/resize-raccoon#1]
I am currently using SRWE, and was looking to replace it with your application.

What's missing?

- Remove Borders
- Fake Fullscreen, so the taskbar is behind the game
- Option to create/save your presets instead of only being able to choose from Triple 1080p, 1440p, and 4k
- Duplicate option for saved profiles, so you only have to rename and select a new process.

**Comment by mistenkt** [comment]
Working on top two, the other two are pretty trivial to add, just not priority for now will tackle them at some point.

**Comment by davidsoucy75** [comment]
In ACC when its switch from the menu screen to the onboard view, it's come back in 1 screen then after like 1 sec reapply the triple, not sure if it's something wrong on my side but if it could stay in tripple full screen it could be nice.

**Comment by mistenkt** [comment]
@MiLeX84  Added borderless now which should solve both issues (v1.6.0), fake fullscreen in SREW doesnt really do anything on its own other than set the window to the full size of the screen which imo doesn't require its own toggle/button, the window size/position with the remove border option will fake full screen for games that are not already running in proper borderless. If anything it can be another preset that already has the width/height/pos of the main screen and labeled as Fullscreen.

Will close this issue, but i will keep the two last feature requests in mind, probably have a look at them this weekend.

@davidsoucy75 make sure you have ACC set to windowedmode or borderless or whatever its option is called (inside ACC video config). If its set to fullscreen it be messing with what RR is doing. I just tested 1.6.0 with borderless enabled on ACC now running triples and it works great.

**Comment by MiLeX84** [comment]
Any ETA on these items?

**Comment by MiLeX84** [comment]
Hey, any updates on this, the app has not received any updates in months, feels like it has already been abandoned.

@mistenkt
