### ISSUE TITLE
ACC Drive HUB

### ISSUE THREAD

**Issue by srevyo** [mistenkt/resize-raccoon#10]
I love RR but there is ab big problem. I cant run RR with acc drive hub. The app is really important for me but it can only show up in windowed mode. RR is using borderless mode and so the App ACC Drive Hub cant display the infos like damage, leaderboard, tyre pressure etc. Is there any chance to use it? 

OH and the other option is alt + enter double tap but this dont work either. It reduces RR to one screen. 

Thank you fpor your work! Really appreciate it! :)

**Comment by mistenkt** [comment]
RR doesn't force borderless. You select whatever rendering mode you want in the game/app. RR works fine with window mode too, and has an option to remove borders from a window if you want.
