### ISSUE TITLE
Unable to read most text in light mode

### ISSUE THREAD

**Issue by davedontmind** [mistenkt/resize-raccoon#15]
I use Windows in light mode, and in that mode the labels and buttons in RR are almost impossible to read - dark grey text on a dark purple/pink background is not a good choice.  I had to look online to find out how to add a profile, because the [+] button is practially invisible so I didn't even see it.

Please adjust colours so that the app is usable in light mode!

**Comment by mistenkt** [comment]
I'll look into this as soon as i find some time, probably just disable the effects that light/dark modes have and just keep it static.

**Comment by mistenkt** [comment]
Fixed in v1.7.0
https://github.com/mistenkt/resize-raccoon/releases/tag/v1.7.0

**Comment by davedontmind** [comment]
Thank you - it's great now!
