### ISSUE TITLE
Inquiry About Future Updates for resize-raccoon

### ISSUE THREAD

**Issue by MiLeX84** [mistenkt/resize-raccoon#16]
Dear @mistenkt,

I wanted to reach out regarding the status of updates for resize-raccoon. I noticed that there haven't been any recent updates since November 21, 2023, despite the roadmap and multiple suggestions that were previously discussed.

I'm genuinely interested in knowing if there are any upcoming developments planned for the app, or if perhaps the focus on its development has shifted. Your insight would be greatly appreciated.

Regards,
Alex

**Comment by mistenkt** [comment]
Hey. I've just been busy with life and other projects but i will try to set aside some time to at least deal with the reported bugs and minor stuff. As for new features i cant promise anything as i just have so much other things on my plate lately, but it is open source for a reason so contributions are welcome.
