### ISSUE TITLE
RFactor 2 becomes a wide boy.

### ISSUE THREAD

**Issue by HypNotiQ4** [mistenkt/resize-raccoon#2]
RF2 becomes super stretched, & unable to click on anything in menus etc.
![TIREZIh](https://github.com/mistenkt/resize-raccoon/assets/114612800/c82bfe28-286e-4838-a77c-ee4ae663321f)

**Comment by mistenkt** [comment]
Haven't actually tried RF2. Did you follow same guides as with SRWE (if RF2 is compatible with that at all). Usually this means setting the game to windowed or borderless via the ingame settings.

**Comment by HypNotiQ4** [comment]
> Haven't actually tried RF2. Did you follow same guides as with SRWE (if RF2 is compatible with that at all). Usually this means setting the game to windowed or borderless via the ingame settings.

Yep, although I don't use SRWE, I just change the resolution in the config file for rf2.

**Comment by mistenkt** [comment]
Looks like RF2 uses a different rendering res from what their window size is (causing this issue). Good news is they actually support setting custom resolutions in their config files so you don't actually need RR/SRWE for RF2. This is only meant to be a solution for the games that don't support setting a custom resolution to a different aspect ratio then what the main monitor has.
