### ISSUE TITLE
Please add a "don't ask again" option. 

### ISSUE THREAD

**Issue by MiLeX84** [mistenkt/resize-raccoon#7]
I only start the app when I want to launch a game that requires this app. Therefore I don't want it in auto start, or sitting in my tray.
It would be nice to have a checkbox like "don't ask again" and a toggle in the settings whether you want the app to close or close to tray. 

![UJd4w5ucye](https://github.com/mistenkt/resize-raccoon/assets/59506850/172abb54-7ea0-4083-b888-6f16bc0db649)

**Comment by mistenkt** [comment]
Fixed in v1.7.0
https://github.com/mistenkt/resize-raccoon/releases/tag/v1.7.0
