### ISSUE TITLE
unable to open Desktop shortcut

### ISSUE THREAD

**Issue by Travie86** [mistenkt/resize-raccoon#8]
Hi, Thank you for setting this up.  A mate of mine recommended this. 
I downloaded the latest version and managed to open the program once.  From there, I am unable to open it.  When I double click on the icon it flashes a window but wont run.  I deleted, tried reinstalling but Im having no success.  Is there any advice you may have. 
Thank you kindly and Happy New Year!

**Comment by Tim1699** [comment]
Hi Travie86, 

Have you had any luck in running the program?
 I'm running into the same issue

**Comment by Travie86** [comment]
Gidday Tim.

I did fix it.

So the allocation was running the whole time.  To find it, it was on the
task bar on the RH side, hover over the ^ and you'll see it there.

**Comment by Tim1699** [comment]
aw nice. thanks man, will try that.
