### ISSUE TITLE
[Feature request] Bezel Correction

### ISSUE THREAD

**Issue by Steel600** [mistenkt/resize-raccoon#9]
Great work ! I was using Nvidia Surround (but not convinced) and I already like Resize Racoon a lot.
I would like to request/suggest a feature : as it's possible to do it in some games (like ACC), or you may not need it if you have a bezel free kit... but for those who don't it would be great to add a feature to add "bezel correction" (like Nvidia Surround does). It allows to correct the bezels on softwares/games that don't have this option, or even on the desktop use.

**Comment by mistenkt** [comment]
Theres no way to fix bezel correction unless the game handles it internally (like ACC).
